sudo: required

services:
  - docker

language: node_js
node_js:
  - '4.1.2'

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - npm install -g
  - soos -b
  - soos -P

script:
  - soos -c /usr/local/bin/npm test

notifications:
  email: false
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"